### ISSUE TITLE
ValueError: states can't be represented as 64-bit unsigned integer

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#178] opened 2019-02-20 11:50 UTC
When I try to find the ground state of two free bosons on two dimensional lattice of size 7x7, the error occured
raise ValueError("states can't be represented as 64-bit unsigned integer")
ValueError: states can't be represented as 64-bit unsigned integer

The minimal code which reproduces the error is attached.
[sample.txt](https://github.com/weinbe58/QuSpin/files/2884480/sample.txt)

Of course, there is an exact solution for this problem. Is it possible to calculate the ground energy for this size of the lattice?

**Comment by mgbukov** [comment] 2019-02-20 15:43
this is a duplicate of #157 , we're working on it.

**Comment by weinbe58** [comment] 2019-02-20 16:16
a work around for the time being would be to use the boson_basis_1d class and not use any symmetries since the size of the H-space is quite small (around 1000 states).

**Comment by weinbe58** [comment] 2019-02-20 21:20
Oooops! it looks like there is a bug in this for python 3 so unfortunately this will have to wait until the new release is finished.

**Comment by mgbukov** [comment] 2019-03-01 19:43
this is fixed in v. 0.3.1

**Closed by mgbukov** 2019-03-01 19:43 UTC
