### ISSUE TITLE
Non-abelian lattice symmetry for ground state

### ISSUE THREAD

**Issue by LinuxDaFaHao** [weinbe58/QuSpin#267] opened 2019-11-13 03:18 UTC
![Lattice](https://user-images.githubusercontent.com/14311138/68731503-4594ad80-060b-11ea-9188-f97667cbbc6a.jpeg)
I meet some problems when calculating the antiferromagnetic triangular Heisenberg model. For 4x4 lattice, the ground state has no degeneracy and with quantum number k=0 and R=exp(i*0*pi)=1, where k is the momentum and R is the generator of C6 rotation. If I impose k=0 and R=1 individually, I can get the correct ground state energy value. But If I impose them at the same time, the results were wrong. By the document, I can ignore the non-abelian property in this case. So is it a bug or is there some mathematical causes I have not considered?

Here is the reference code.

`from quspin.operators import hamiltonian
from quspin.basis import spin_basis_general # spin basis constructor
import numpy as np # general math functions

###### define model parameters ######
N_2d = 16 # number of sites
Lx, Ly=4,4
J=1 # spin=spin interaction

nup=8 # number of spin up, =Sz+8
z=0    # spin inversion symmetry, 0,1
kx=0   # translation symmetry in  direction
r=0     # Rotaion pi/3 symmetry, 0,1,2,3,4,5

print('Symmetry Sector:')
print('    Sz    =    %d'%(nup-8))
print('    Spin inversion symmetry=%d'%(z))

###### setting up user-defined symmetry transformations for 2d lattice ######
s = np.arange(N_2d) # sites [0,1,2,....]
x = s%Lx # x positions for sites
y = s//Lx # y positions for sites
T_x = (x+1)%Lx + Lx*y # translation along x-direction
T_x2 = (x+2)%Lx + Lx*y # translation along x-direction
T_y = x +Lx*((y+1)%Ly) # translation along y-direction
T_y2 = x +Lx*((y+2)%Ly) # translation along y-direction
T_y2x1 = (x+1)%Lx +Lx*((y+2)%Ly)
T_y1x2 = (x+2)%Lx +Lx*((y+1)%Ly)
T_45= (x+1)%Lx + Lx*((y+1)%Ly)  # translation along diagonal direction
Z   = -(s+1) # spin inversion
R_pi3 =[0,5,10,15,3,4,9,14,2,7,8,13,1,6,11,12]

##### setting up site-coupling lists
J_hei=[[J,i,T_x[i]] for i in range(N_2d)]+[[J,i,T_y[i]] for i in range(N_2d)]+[[J,i,T_45[i]] for i in range(N_2d)]
J_hei2=[[J/2,i,T_x[i]] for i in range(N_2d)]+[[J/2,i,T_y[i]] for i in range(N_2d)]+[[J/2,i,T_45[i]] for i in range(N_2d)]

static=[["zz",J_hei],["+-",J_hei2],["-+",J_hei2]]

##### Only set quantum number kx=0
basis_2d = spin_basis_general(N_2d,Nup=nup,pauli=0,kxblock=(T_x,kx),zblock=(Z,z))
H=hamiltonian(static,[],basis=basis_2d,dtype=np.float64)
E=(H.eigsh(k=min(3,H.Ns),which='SA',tol=1E-14,maxiter=1E5,return_eigenvectors=False))/N_2d
print('The lowest energies in kx=0 sector:')
for i in range(3):
    print('%.15f'%(E[i]))

###### Only set quantum number r=0
basis_2d = spin_basis_general(N_2d,Nup=nup,pauli=0,R3block=(R_pi3,r),zblock=(Z,z))
H=hamiltonian(static,[],basis=basis_2d,dtype=np.float64)
E=(H.eigsh(k=min(3,H.Ns),which='SA',tol=1E-14,maxiter=1E5,return_eigenvectors=False))/N_2d
print('The lowest energies in r=0 sector:')
for i in range(3):
    print('%.15f'%(E[i]))

###### set quantum number r=0 and kx=0 simultaneously
basis_2d = spin_basis_general(N_2d,Nup=nup,R3block=(R_pi3,r),kxblock=(T_x,kx),zblock=(Z,z)) # R_pi3 and T_x are not commute
H=hamiltonian(static,[],basis=basis_2d,dtype=np.float64)
E=(H.eigsh(k=min(3,H.Ns),which='SA',tol=1E-14,maxiter=1E5,return_eigenvectors=False))/N_2d
print('The lowest energies in kx=0, r=0 sector:')
for i in range(3):
    print('%.15f'%(E[i]))
`

**Comment by weinbe58** [comment] 2019-11-13 03:34
Could you post a picture of the cluster of sites you're using?

**Comment by LinuxDaFaHao** [comment] 2019-11-13 03:50
> Could you post a picture of the cluster of sites you're using?

I draw it by hand. Please see it on the first floor

**Comment by weinbe58** [comment] 2019-11-13 03:59
I see, so the issue is that the rotation does not preserve the global symmetry of the cluster. 

Sometimes a cluster will not have all the symmetries of the infinite lattice. In this case, you have to use the subgroup of C6, which consists of the two reflection axes of the cluster. 

```
from quspin.operators import hamiltonian
from quspin.basis import spin_basis_general # spin basis constructor
import numpy as np # general math functions

###### define model parameters ######
N_2d = 16 # number of sites
Lx, Ly=4,4
J=1 # spin=spin interaction

nup=8 # number of spin up, =Sz+8
z=0    # spin inversion symmetry, 0,1
kx=0   # translation symmetry in  direction
ky=0   # translation symmetry in  direction
p_1 = 0
p_2 = 0

print('Symmetry Sector:')
print('    Sz    =    %d'%(nup-8))
print('    Spin inversion symmetry=%d'%(z))

###### setting up user-defined symmetry transformations for 2d lattice ######
s = np.arange(N_2d) # sites [0,1,2,....]
x = s%Lx # x positions for sites
y = s//Lx # y positions for sites
T_x = (x+1)%Lx + Lx*y
T_y = x + Lx*((y+1)%Ly)
P_1 = y + Lx*x
P_2 = (Lx-x-1)+Lx*(Ly-y-1)
Z = -(np.arange(N_2d)+1)

T_nn_1 = T_x
T_nn_2 = T_y
T_nn_3 = (x-1)%Lx+Lx*((y+1)%Ly)

##### setting up site-coupling lists
J_hei=[[1.0,i,T[i]] for i in range(N_2d) for T in [T_nn_1,T_nn_2,T_nn_3]]

static=[["zz",J_hei],["xx",J_hei],["yy",J_hei]]


basis_2d = spin_basis_general(N_2d,Nup=nup,pauli=0,kxblock=(T_x,kx),kyblock=(T_y,ky),zblock=(Z,z))
H=hamiltonian(static,[],basis=basis_2d,dtype=np.float64)
E=(H.eigsh(k=min(3,H.Ns),which='SA',tol=1E-14,maxiter=1E5,return_eigenvectors=False))/N_2d
print('The lowest energies in kx=0 sector:')
for i in range(3):
    print('%.15f'%(E[i]))


basis_2d = spin_basis_general(N_2d,Nup=nup,pauli=0,kxblock=(T_x,kx),kyblock=(T_y,ky)
	,p1block=(P_1,p_1),p2block=(P_2,p_2),zblock=(Z,z))
H=hamiltonian(static,[],basis=basis_2d,dtype=np.float64)
E=(H.eigsh(k=min(3,H.Ns),which='SA',tol=1E-14,maxiter=1E5,return_eigenvectors=False))/N_2d
print('The lowest energies in r=0 sector:')
for i in range(3):
    print('%.15f'%(E[i]))

```

This code works; however, I am fiding a weird bug that if you do not include the `T_y` and `T_x` symmetry at the same time, the energies do not work out. I believe this is because when you perform the reflections, `T_x` goes to `T_y` and vice-versa.

**Comment by LinuxDaFaHao** [comment] 2019-11-13 08:55
> I see, so the issue is that the rotation does not preserve the global symmetry of the cluster.
> 
> Sometimes a cluster will not have all the symmetries of the infinite lattice. In this case, you have to use the subgroup of C6, which consists of the two reflection axes of the cluster.
> 
> ```
> from quspin.operators import hamiltonian
> from quspin.basis import spin_basis_general # spin basis constructor
> import numpy as np # general math functions
> 
> ###### define model parameters ######
> N_2d = 16 # number of sites
> Lx, Ly=4,4
> J=1 # spin=spin interaction
> 
> nup=8 # number of spin up, =Sz+8
> z=0    # spin inversion symmetry, 0,1
> kx=0   # translation symmetry in  direction
> ky=0   # translation symmetry in  direction
> p_1 = 0
> p_2 = 0
> 
> print('Symmetry Sector:')
> print('    Sz    =    %d'%(nup-8))
> print('    Spin inversion symmetry=%d'%(z))
> 
> ###### setting up user-defined symmetry transformations for 2d lattice ######
> s = np.arange(N_2d) # sites [0,1,2,....]
> x = s%Lx # x positions for sites
> y = s//Lx # y positions for sites
> T_x = (x+1)%Lx + Lx*y
> T_y = x + Lx*((y+1)%Ly)
> P_1 = y + Lx*x
> P_2 = (Lx-x-1)+Lx*(Ly-y-1)
> Z = -(np.arange(N_2d)+1)
> 
> # nearest neighbor transformations
> T_nn_1 = T_x 
> T_nn_2 = T_y
> T_nn_3 = (x-1)%Lx+Lx*((y+1)%Ly)
> 
> ##### setting up site-coupling lists
> J_hei=[[1.0,i,T[i]] for i in range(N_2d) for T in [T_nn_1,T_nn_2,T_nn_3]]
> static=[[op,J_hei] for op in ["xx","yy","zz"]]
> 
> 
> basis_2d = spin_basis_general(N_2d,Nup=nup,pauli=0,kxblock=(T_x,kx),kyblock=(T_y,ky),zblock=(Z,z))
> H=hamiltonian(static,[],basis=basis_2d,dtype=np.float64)
> E=(H.eigsh(k=min(3,H.Ns),which='SA',tol=1E-14,maxiter=1E5,return_eigenvectors=False))/N_2d
> print('The lowest energies in kx=0 sector:')
> for i in range(3):
>     print('%.15f'%(E[i]))
> 
> 
> basis_2d = spin_basis_general(N_2d,Nup=nup,pauli=0,kxblock=(T_x,kx),kyblock=(T_y,ky)
> 	,p1block=(P_1,p_1),p2block=(P_2,p_2),zblock=(Z,z))
> H=hamiltonian(static,[],basis=basis_2d,dtype=np.float64)
> E=(H.eigsh(k=min(3,H.Ns),which='SA',tol=1E-14,maxiter=1E5,return_eigenvectors=False))/N_2d
> print('The lowest energies in r=0 sector:')
> for i in range(3):
>     print('%.15f'%(E[i]))
> ```
> 
> In this case, `P_1` and `P_2` are reflections about the two diagonals of the cluster. This code works; however, I am fiding a weird bug that if you do not include the `T_y` and `T_x` symmetry at the same time, the energies do not work out. I believe this is because when you perform the reflections, `T_x` goes to `T_y` and vice-versa.


Very thanks for the reply. But I think the rotation symmetry is also preserved in this finite system. The rotation operator, named `R_pi3` in my code, is a symmetry operation. Does this package automatically check the symmetry? I can also write it in the form:
0 --> 0
2 --> 10 --> 8 --> 2
1 --> 5 --> 4 --> 3 --> 15 --> 12 --> 1

I haven't read the source code of the package but I think it is excellent work. So I am not sure how do you realize the symmetry. But I think it's not easy to impose `T_x` and rotation symmetry at the same time, even in the k_x=0 sector.  For example, there is a configuration
1--1--1--1
  \    \    \    \
   0--0--0--0
     \     \     \     \
        1--1--1--1
          \    \    \    \
           0--0--0--0
which is translation invariance along the x-direction. But we can not construct a rotation invariance state starting from this state in the k_x=0 sector. It may involve high-dimensional irreducible representation such that the program can not work. The same argument is also suitable for `P_1` and `P_2` in your example.

Hoping you have a nice day.

**Comment by weinbe58** [comment] 2019-11-13 17:10
basically the code generates the group but cycling through all configurations of the symmetry operations acting on the state and picks the largest integer as the representative for that group of states. I think a problem can happen when that group is not complete in the sense that some states are not represented. In this case, the code can't construct a hermitian matrix because some states that it encounters do not fall in that group and therefore do not have a matrix element. 

The specific issue with your code is that you do not include T_y into the symmetry list, remember T_x transforms into T_y under rotation so by not including that symmetry you're excluding a whole part of the group structure. 
In fact when I add T_y in the last part in your original code it does reproduce the correct ground state.

**Comment by weinbe58** [comment] 2019-11-13 17:24
There are two things,

1) you need to include T_y in the symmetry list because T_x -> T_y under rotations and by ecluding it you are missing part of the group structure which leads to a non-hermitian matrix (check by looking at H-H.H)
2) you forgot to set `pauli=0` in your basis for the last one so your matrix elements are off by a factor of 4.

**Comment by LinuxDaFaHao** [comment] 2019-11-14 04:04
> There are two things,
> 
> 1. you need to include T_y in the symmetry list because T_x -> T_y under rotations and by excluding it you are missing part of the group structure which leads to a non-hermitian matrix (check by looking at H-H.H w/ and w/o having T_y)
> 2. you forgot to set `pauli=0` in your basis for the last one so your matrix elements are off by a factor of 4.
> 
> If you add these in your code give sensible results.
> 
> That is interesting though that you can do the full rotation group, but I believe you should be able to do the full D6 point group by including some reflections as well.

Yeah. I understand now. I must specify the momentum in the First Brillouin Zone, then select a little group commuting with the translation operators to impose more symmetry. As you said, I should set ky=0 then it works. 

I also tried imposing all the D6 symmetry for the ground state and it works well. Thank you very much.

**Comment by weinbe58** [comment] 2019-11-14 19:01
OK good, I'm gonna close this since everything is working.

**Closed by weinbe58** 2019-11-14 19:01 UTC

**Comment by mgbukov** [comment] 2019-11-14 23:19
Do you guys think it would be beneficial to create an example of the triangular lattice to put online? I wonder if it is too special or not in this case.
