### ISSUE TITLE
Unable to use get_vec in spinful_fermion_basis_general

### ISSUE THREAD

**Issue by srujans** [weinbe58/QuSpin#151] opened 2018-10-13 15:32 UTC
Hello Developers,
I am getting an error while using get_vec function in spinful_fermion_basis_general module:

from quspin.basis import spinful_fermion_basis_general

v_full =get_vec(V)

The program is unable to recognize the get_vec function even after importing  above basis. 

![capture](https://user-images.githubusercontent.com/12464481/46907035-1accb700-cf2a-11e8-80ea-3d0e3de27062.PNG)

My final goal is to evolve the ground state and calculate the correlation functions. For that I am transforming my state from symmetry reduced basis to full basis and then evolve it (I am evaluating time evolved state according to some other Hamiltonian).

Any form of help is appreciated in this regard. Thank You.

**Comment by mgbukov** [comment] 2018-10-13 15:45
Hi,

the get_vec function is a method of the basis class. When u create the
basis object using , try calling it by

basis=spinful_fermion_...()
basis.get_vec(...)

If u still get an error message after trying this, could u upload a short
code which we can run to debug the problem?

Thanks
Marin

Marin

**Comment by srujans** [comment] 2018-10-13 16:32
Hello Marin,
Thanks for the response.
Actually I have been using  the class name as evident from the following example.
[upload.txt](https://github.com/weinbe58/QuSpin/files/2475642/upload.txt)
But now I am getting the error: 
![capture](https://user-images.githubusercontent.com/12464481/46907666-a565e400-cf33-11e8-8e33-d88a5d2645c0.PNG)

Thank You.

**Comment by mgbukov** [comment] 2018-10-14 01:32
@srujans : u seem to call the `gev_vec()` method the wrong way. Function methods of basis classes are called by first constructing a basis object, and then using the object to call the method, i.e.:

`basis_2d=spinful_fermion_basis_general(N_2d,Nf=(2,2),kxblock=(T_x,0),kyblock=(T_y,0),sblock=(S,0))`
`v_full =basis_2d.get_vec(V)`

This is because u need to instantiate the class first. If u do not do this (as u did in `spinful_fermion_basis_general.get_vec(V)`, then python expect two arguments: `self` and the usual argument (here `V`). 

@weinbe58  : there is indeed a bug with the `get_proj_helper_32` class in `general_basis_core.pyx`. The error is raised when u call `_sp.csr_matrix` and has to do with inconsistent shape of the array, so it's probably easy to fix. 

I'm attaching a simple code to reproduce the bug
[bug.txt](https://github.com/weinbe58/QuSpin/files/2476000/bug.txt)

**Comment by srujans** [comment] 2018-10-15 16:03
@mgbukov 👍 Yes, I apologize for that blunder in the code. I fixed that error.

But now I am getting an error in basis dimension:

1) Lx,Ly=4,4: ValueError: row index exceeds matrix dimensions
2) Lx,Ly=2,2: ValueError: negative row index found
3) Lx,Ly=2,3: ValueError: negative row index found

Infact, for any value of (Lx,Ly), other than 4, I am getting the same error.

PS: Above error can be seen if you change the Lx,Ly values in the sample code that you posted (bug.txt)

Thanks!!

**Comment by weinbe58** [comment] 2018-12-13 22:57
fixed in #156

**Comment by mgbukov** [comment] 2018-12-31 06:50
@weinbe58 I think there's still a bug left with the general `get_proj` and `get_vec` functions.

I got an email today from a guy using the `spinless_fermion_general` reporting a mismatch in the dimensions of the projector (compared to the case w/o symmetries). I'm attaching a script showing the mismatch.

It's likely some array size preallocation issue with `get_proj`, because the guy said "There are lots of zeros values in the full basis wavefunction. After deleting the zeros, I can get the correct wavefuntion."

Here's the script:
[ED2DSpinless.txt](https://github.com/weinbe58/QuSpin/files/2717817/ED2DSpinless.txt)

**Comment by mgbukov** [comment] 2018-12-31 15:32
I looked carefully into this, there is NO bug. The confusion comes because the general `get_vec` and `get_proj` go all the way up to the symmetry-free `sps**Ns`-sized basis and ignore any residual particle conservation.  

It would still be nice to add the `p_con` argument to the general `get_proj`, see issue #94 . Currently, the `basis_1d.get_proj()` has the `pcon` optional argument but the `general_basis.get_proj()` does not. `get_vec()` does not have a `pcon` argument in any basis class.

**Comment by weinbe58** [comment] 2018-12-31 15:34
Yes I realized this back when I created the general basis function. maybe for now in order to stop the confusion we can add the flag to the function but have it raise a NotImplementedError.

**Comment by mgbukov** [comment] 2018-12-31 15:40
OK, I'll do that. 

But is there any fundamental reason why this is hard to implement? It seems to me that we can apply two projectors consecutively P1^\dagger*P2|psi_reduced>, where P2 brings the state to the full 2^N H_space (what the function currently does) and P1^\dagger then reduces the state again to the particle conserved basis. It's not efficient cuz we need to construct a new basis to get P1, but it should do the job?

**Comment by weinbe58** [comment] 2018-12-31 15:46
Well its possible to do that, however that's not always possible, for example if I am doing a single particle hamiltonian with 1000 sites it will never be possible to construct the projector with SciPy going from the single particle sector to the full 2^1000 state sector. 

Its not hard to implement this for the general basis, however it would require me to write a new function and at the time I just wanted to get the class finished up first.

**Comment by mgbukov** [comment] 2018-12-31 15:49
fair enough!

How about that: I'll put a NonImplemented Error and leave a message before the error is raised that they can essentially do this manually in two steps by creating a new basis object, if they need to.

**Comment by mgbukov** [comment] 2018-12-31 18:17
OK, I added the `pcon` optional argument with the `NotImplementedError` and a suggestion how to circumvent this issue is needed. 

Closing this issue, since we have #94 open.

**Closed by mgbukov** 2018-12-31 18:17 UTC
