### ISSUE TITLE
Quspin does not support Python 3.8

### ISSUE THREAD

**Issue by mhasan-optics** [weinbe58/QuSpin#379] opened 2020-12-31 20:56 UTC
The installation complains that I have a more updated version of python. What do you suggest on this!

**Comment by mgbukov** [comment] 2020-12-31 21:43
Wait for the next release (coming up in January). In the meantime you may
use py37.

Or, build the code manually from source -- I was able to successfully build
it in mac os x with py38.

**Comment by mhasan-optics** [comment] 2021-01-03 09:48
Thank you!

**Comment by mgbukov** [comment] 2021-01-07 08:25
This is a duplicate of #366  so I'm closing it.

**Closed by mgbukov** 2021-01-07 08:25 UTC
