### ISSUE TITLE
spin_1d_basis._non_zero is broken for S > 1/2

### ISSUE THREAD

**Issue by jaredjeya** [weinbe58/QuSpin#290] opened 2019-12-20 17:01 UTC
This method appears to be designed to remove repeated S+ or S- operators - which only makes sense for S = 1/2, where (S+)^2 =(S-)^2 = 0. 

However, when S > 1/2, this is not true, and in fact (S+)^n = (S-)^n = 0 only for n > 2S. This leads to non-zero terms being erroneously marked as zero by this method. I was using S = 1 and getting issues due to this bug.

The fix is incredibly simple (two lines):

    def _non_zero(self,op):
        opstr = _np.array(list(op[0]))
        indx = _np.array(op[1])
            if _np.any(indx>=0):
                indx_p = indx[opstr == "+"].tolist()
                p = not any(indx_p.count(x) > self._sps - 1 for x in indx_p)  #
                indx_p = indx[opstr == "-"].tolist()
                m = not any(indx_p.count(x) > self._sps - 1 for x in indx_p) #
                return (p and m)
            else:
                return True

The two `#` mark lines where I've replaced `1` by `self._sps - 1`. This fixed the issue for me and I'm fairly sure this should generalise for any value of the spin.

**Comment by mgbukov** [comment] 2019-12-20 17:33
Many thanks for reporting this, and sorry about the confusion caused! We'll fix it in the next release. 

Could you post a minimal example script which reproduces the bug? I'd like to add it to the tests to make sure any future changes/updates respect this. 

Also, you may consider submitting an official pull request with this change (pls pull the master branch, make the change in the code, and submit the request into the dev_0.3.4 branch). 

We're looking for people interested in contributing to quspin, so any further suggestions/bug fixes/enhancements, etc are very welcome!

**Comment by weinbe58** [comment] 2019-12-24 21:21
@mgbukov actually this is a good point to just move this function into the lattice class since all the lattice basis objects have this generically.

**Comment by mgbukov** [comment] 2020-01-01 01:44
@weinbe58 did you fix this issue, or should I take care of it?

**Comment by weinbe58** [comment] 2020-01-02 12:35
@mgbukov It should be fixed in pull request #291

**Closed** 2020-04-17 14:38 UTC
